parameters:
    env(VARNISH_URL): ''

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    collection:
        order_parameter_name: order # the URL query parameter to use is now "_order"
        pagination:
            enabled: true

            client_enabled: true
            enabled_parameter_name: pagination # optional

            items_per_page: 10 # Default value

            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value

            maximum_items_per_page: 100

#            partial: true # Disabled by default

#            client_partial: true # Disabled by default
#            partial_parameter_name: 'partial' # Default value

