security:
  role_hierarchy:
    ROLE_CUSTOMER: ROLE_USER
    ROLE_ADMIN: ROLE_CUSTOMER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    apiLogin:
      pattern:   ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path: api_login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern:   api
      stateless: true
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    main:
      pattern: ^/
      user_checker: security.user_checker
      form_login:
        provider: fos_userbundle
#        csrf_token_generator: security.csrf.token_manager
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        success_handler: app.security.authentication_handler
        failure_handler: app.security.authentication_handler
      logout:
        path: fos_user_security_logout
        target: home_page_action
      anonymous:    true

  access_control:
    # TODO: API - GÜWENLİK DIŞI KALAN URL ALANI
    - { path: ^/(%locales%)/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobil-function/register, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobil-function/test, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobil-function/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobil-function/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobil-function/test-moc-data, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: API - GÜWENLİK DIŞI KALAN URL ALANI BİTİŞ

    # TODO: API - GÜWENLİKLİ URL ALANI
#    - { path: ^/(%locales%)/api, roles: IS_AUTHENTICATED_FULLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: API - GÜWENLİKLİ URL ALANI BİTİŞ

# -------------------------------------------------------------------------------------------------------------------------------

    # TODO: WEB ADMIN - GÜWENLİK DIŞI KALAN URL ALANI
    - { path: ^/(%locales%)/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/admin/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/admin/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/admin/forgott-password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/admin/change-password, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: WEB ADMIN - GÜWENLİK DIŞI KALAN URL ALANI BİTİŞ

    # TODO: WEB ADMIN - GÜWENLİKLİ URL ALANI
    - { path: ^/(%locales%)/admin, roles: ROLE_ADMIN, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: WEB ADMIN - GÜWENLİKLİ URL ALANI BİTİŞ

# -------------------------------------------------------------------------------------------------------------------------------

    # TODO: WEB FRONT - GÜWENLİKLİ URL ALANI
#    - { path: ^/(%locales%)/shopping-cart, roles: IS_AUTHENTICATED_FULLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: WEB FRONT - GÜWENLİKLİ URL ALANI BİTİŞ

    # TODO: WEB FRONT - GÜWENLİK DIŞI KALAN URL ALANI
    - { path: ^/(%locales%)/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%'}
    # TODO: WEB FRONT - GÜWENLİK DIŞI KALAN URL ALANI BİTİŞ
