# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(LOCALE)%'
    locales: '%env(LOCALES)%'
    container.dumper.inline_factories: true
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests}'
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
  Sg\DatatablesBundle\Datatable\DatatableFactory:
    class: Sg\DatatablesBundle\Datatable\DatatableFactory
    public: true
    arguments:
      - '@security.authorization_checker'
      - '@security.token_storage'
      - '@translator'
      - '@router'
      - '@doctrine.orm.entity_manager'
      - '@twig'
  Sg\DatatablesBundle\Response\DatatableResponse:
    class: Sg\DatatablesBundle\Response\DatatableResponse
    public: true
    arguments:
      - '@request_stack'
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
  Gedmo\Loggable\Entity\LogEntry:
    class: Gedmo\Loggable\Entity\LogEntry
  App\EventListener\LoginListener:
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
  security.logout.handler.session:
    class: App\EventListener\SessionLogoutHandler
    arguments:
      - "@fos_user.user_manager"
      - "@doctrine.orm.entity_manager"
      - "@SessionHandlerInterface"
  app.service.seflinkprocessor:
    public: true
    class: App\Service\SefLinkProcessor
    arguments:
      - '@translator'
      - '@doctrine.orm.entity_manager'
      - '@service_container'
      - '@request_stack'
#-TODO: ENTITY LISTENER CONSTRUCT 'A DATA YOLLAMAK İÇİN -----------------BAŞLANGIÇ--------------------------------------------------
  app.eventlistener.userlistener:
    public: true
    class: App\EventListener\UserListener
    tags:
      - { name: doctrine.orm.entity_listener, lazy: true }
    arguments:
      - "@security.token_storage"
      - "@service_container"
  #-TODO: ENTITY LISTENER CONSTRUCT 'A DATA YOLLAMAK İÇİN -----------------BİTİŞ--------------------------------------------------
  app.service.base64extractor:
    public: true,
    class: App\Service\Base64FileExtractor
  app.service.imageprocessor:
    public: true
    class: App\Service\ImageProcessor
    arguments:
      - "@service_container"
      - "@app.service.base64extractor"
  app.service.dataconverterprocessor:
    public: true
    class: App\Service\DataConverterProcessor
    arguments:
      - "@service_container"
  app.service.mailprocessor:
    public: true
    class: App\Service\MailProcessor
    arguments:
      - "@service_container"
      - "@swiftmailer.mailer"
      - "@twig"
  app.security.authentication_handler:
    class: App\Service\AuthenticationHandler
    public: false
    arguments:
      - "@router"
      - "@session"
  app.dbal.jsonobject:
    class: App\DBAL\JsonObject
    public: true
    arguments:
      - "JSON_OBJECT"
  App\Twig\Extension\JsonDecode:
    class: App\Twig\Extension\JsonDecode
    tags:
      - { name: twig.extension }
