<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOcgfJfx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOcgfJfx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOcgfJfx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOcgfJfx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOcgfJfx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OcgfJfx',
    'container.build_id' => '00772a50',
    'container.build_time' => 1627858334,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOcgfJfx');
